name: Format Scan

on:
  pull_request:
    branches: [main]
    paths:
      - intel_extension_for_transformers
      - setup.py
      - .github/workflows/format_scan.yml
      - .github/workflows/script/formatScan
  workflow_dispatch:

# If there is a new commit, the previous jobs will be canceled
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  DOCKER_CONFIG_NAME: "commonDockerConfig"
  REPO_NAME: "code-scan"
  REPO_TAG: "1.0"
  DOCKER_FILE_NAME: "codeScan"
  CONTAINER_NAME: "codeScan"

jobs:
  format-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_name: [
            "pylint",
            "bandit",
            "clangformat",
            "cloc",
            "cpplint",
            # "pydocstyle",
            "pyspelling",
          ]
      fail-fast: false
    steps:
      - name: Docker Clean Up
        run: |
          docker ps -a
          if [[ $(docker ps -a | grep -i '${{ env.CONTAINER_NAME }}'$) ]]; then
              docker start $(docker ps -aq)
              echo "remove left files through container ..."
              docker exec ${{ env.CONTAINER_NAME }} bash -c "ls -a /intel-extension-for-transformers && rm -fr /intel-extension-for-transformers/* && rm -fr /intel-extension-for-transformers/.* || true"
          fi
          
      - name: Checkout out Repo
        uses: actions/checkout@v3

      - name: Docker Build
        run: |
          docker build -f ${{ github.workspace }}/.github/workflows/docker/${{ env.DOCKER_FILE_NAME }}.dockerfile -t ${{ env.REPO_NAME }}:${{ env.REPO_TAG }} .

      - name: Docker Run
        run: |
          if [[ $(docker ps -a | grep -i '${{ env.CONTAINER_NAME }}'$) ]]; then
            docker stop $(docker ps -aq)
            docker rm -vf ${{ env.CONTAINER_NAME }} || true
          fi
          docker run -dit --disable-content-trust --privileged --name=${{ env.CONTAINER_NAME }} -v /dev/shm:/dev/shm \
          -v ${{ github.workspace }}:/intel-extension-for-transformers \
          ${{ env.REPO_NAME }}:${{ env.REPO_TAG }}
          echo '${{ toJSON(github) }}'

      - name: Env build
        run: |
          docker exec ${{ env.CONTAINER_NAME }} \
          bash /intel-extension-for-transformers/.github/workflows/script/prepare_env.sh

      - name: Code scan check
        run: |
          docker exec ${{ env.CONTAINER_NAME }} \
          bash -c "bash /intel-extension-for-transformers/.github/workflows/script/formatScan/${{ matrix.job_name }}.sh"

      - name: Publish pipeline artifact
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.job_name }}
          path: ${{ github.workspace }}/.github/workflows/script/formatScan/${{ matrix.job_name }}.*
