name: Trellix Command Line Scanner

on:
  workflow_dispatch:

jobs:
  Trellix:
    runs-on: inner-source
    steps:
      - name: Clean Up Working Directory
        run: sudo rm -rf ${{github.workspace}}/*

      - name: Checkout out Repo
        uses: actions/checkout@v4

      - name: Run Trellix Scanner
        env:
          workspace: ${{ github.workspace }}
        run: bash .github/workflows/script/formatScan/trellix.sh

      - name: Publish pipeline artifact
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}/.github/workflows/script/formatScan/report.html
